global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "compliance_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["compliance_api:8000"]
        labels:
          service: "ai-compliance-checker"
